export { default as homepage1 } from '../assets/images/homepage_1.jpg'
export { default as homepage2 } from '../assets/images/homepage_2.jpg'
export { default as services2 } from '../assets/images/services2.jpg'
export { default as datepicker } from '../assets/images/date-picker.svg'
export { default as scanqr } from '../assets/images/scanqr.jpg'
export { default as store } from '../assets/images/store.png'
export { default as play } from '../assets/images/play.png'
export { default as spinner } from '../assets/images/spinner.svg'